---
apiVersion: v1
kind: Service
metadata:
  name: mailslurper
  labels:
    app.kubernetes.io/name: mailslurper
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4436
      targetPort: 4436
      name: www
    - protocol: TCP
      port: 4437
      targetPort: 4437
      name: service
    - protocol: TCP
      port: 1025
      targetPort: 1025
      name: smtp
  selector:
    app.kubernetes.io/name: mailslurper
